<a href="https://colab.research.google.com/github/WonJunPark/2019-Gsoftware-Challenge/blob/master/algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 4월 8일 알고리즘 수업
- 김우성 교수님

### 선택정렬

In [0]:
a = [29,10,14,37,13]
n = len(a)
result = selectionSort(a,n)
print('선택정렬 결과 :',result)

loop.. :  [29, 10, 14, 13, 37]
loop.. :  [13, 10, 14, 29, 37]
loop.. :  [13, 10, 14, 29, 37]
loop.. :  [10, 13, 14, 29, 37]
loop.. :  [10, 13, 14, 29, 37]
선택정렬 결과 : [10, 13, 14, 29, 37]


In [0]:
def selectionSort(a,n):

  max_ = a[0]

  for i in range(n-1,-1,-1):
    # 4~0 까지 루프
    # 최댓값 인댁스
    max_index = i

    # 최댓값 인덱스 찾기
    for j in range(0,i):
      if a[j] > a[max_index]:
        max_index = j
    
    # 스위치
    a[i], a[max_index] = a[max_index], a[i]
    print('loop.. : ',a)
  
  return a

### 병합정렬

In [0]:
a = [7,2,9,4,3,8,6,1]
mergeSort(a)

[1, 2, 3, 4, 6, 7, 8, 9]

In [0]:
def mergeSort(a):
    # a의 길이가 1 이상일 때
    if len(a)>1:
        # 중간 지점을 구함
        mid = len(a)//2

        # 중간 지점을 기준으로 좌우를 나눔 
        left = a[:mid]
        right = a[mid:]

        # 전반부, 후반부 정렬
        left2 = mergeSort(left)
        right2 = mergeSort(right)

        # merge함수를 불러와서 병합
        return merge(left2, right2)
    else:
        return a


In [0]:
def merge(left, right):
  # 임의의 두 변수를 선언
  # 이 두값이 리스트내 값을 비교하는 지표가됨
  i = 0
  j = 0

  # 결과값을 받은 리스트
  merge_a = []

  # 좌우를 비교하여 작은값을 결과 리스트에 추가
  while (i<len(left)) & (j<len(right)):
      if left[i] < right[j]:
          merge_a.append(left[i])
          i+=1
      else:
          merge_a.append(right[j])
          j+=1
  
  # 나머지 값들을 결과 리스트에 추가
  while (i<len(left)):
      merge_a.append(left[i])
      i+=1
  
  while (j<len(right)):
      merge_a.append(right[j])
      j+=1
      
  return merge_a
    

## 4월 22일 알고리즘 수업

### 퀵 정렬

In [0]:
a = [7,2,9,4,3,8,6,1]
quick_sort(a)

[1, 2, 3, 4, 6, 7, 8, 9]

In [0]:
def quick_sort(a):
  # a의 길이가 2 이상일 때,
  if len(a) > 1:
    pivot = a[0]
    # pivot을 기준으로 작은값은 left, 크거나 같은 값은 right 변수에 담는다.
    left = [e for e in a[1:] if e < pivot]
    right = [e for e in a[1:] if e >= pivot]
    # pivot을 기준으로 left, right 리스트를 병합하고 재귀함수를 실행한다.
    return quick_sort(left) + [pivot] + quick_sort(right)

  else :
    return a

## 4월 29일 알고리즘 수업

### 힙 정렬

- 힙 성질이란? 크기(우선 순위)를 중심으로 정렬
- 힙은 한 노드가 최대 두개의 자식노드를 가지면서 마지막 레벨을 제외한 모든 레벨에서 완전 이진트리
- 힙 구조를 만들어야 힙 정렬을 할 수 있음
- ref1. https://lsjsj92.tistory.com/472
- ref2. https://ratsgo.github.io/data%20structure&algorithm/2017/09/27/heapsort/

#### 1. 힙 정렬 함수

In [0]:
def heap_sort(unsorted):
    # 리스트에 전체 길이를 받음
    n = len(unsorted)

    # // 연산자 : 몫 구하기
    # 이진트리를 구하기 때문에 전체 크기의 반만 반복
    # for문을 거꾸로 돌아감
    # 이진트리의 가장 아래서부터 heapifyt를 실행하여 힙 구조를 만듬

    ### 첫번째 루프 따라가기
    ### [loop1]. input shape : 8 // unsorted = [7,2,9,4,3,8,6,1]
    ### [loop1]. for i in range(3,-1,-1)
    for i in range(n // 2 - 1, -1, -1):
        ### [loop1]. heapify(unsorted 리스트, i값인 3, 전체 길이 8)
        ### [loop1]. heapify 함수로 이동
        heapify(unsorted, i, n)

    # 마지막 노드부터 루트노드를 기준으로 값을 스위치하면서 정렬

    ### [loop1]. 현재 unsorted의 값 [9, 8, 7, 6, 3, 2, 4, 1]
    ### [loop1]. for i in range(7, 0, -1)
    for i in range(n - 1, 0, -1):
        ### [loop1]. unsorted[0] = 1, unsorted[7] = 9
        unsorted[0], unsorted[i] = unsorted[i], unsorted[0]
        ### [loop1]. unsorted의 값 [1, 8, 7, 6, 3, 2, 4, 9]
        ### [loop1]. heapify(unsorted, 0, 7)
        ### [loop1]. 다시 heapify로 가서 정렬
        heapify(unsorted, 0, i)
        ### [loop1].힙 정렬 후, 역순으로 큰값을 끝으로 밀어넣어줌
    return unsorted

#### 2. 힙 구조 함수

In [0]:
# 힙 성질을 확인 후 재정렬
# unsorted : 배열, index : 인덱스, heap_size : 크기

### [loop1]. heapify(a 리스트, i값인 3, 전체 길이 8)
def heapify(unsorted, index, heap_size):

    ### [loop1]. largest = 3
    ### [loop1]. unsorted[3] = 4
    largest = index

    ### [loop1]. left_index = 6 // unsorted[6] = 6
    ### [loop1]. right_index = 7 // unsorted[7] = 1
    left_index = 2 * index
    right_index = 2 * index +1

    # 자식노드가 범위안에 드는지 확인, 자식노드가 부모노드보다 큰지 확인
    # 자식노드가 부모노드보다 크다면 인덱스 스위치

    ### [loop1]. unsorted[left_index] = 6, unsorted[largest] = 3
    if left_index < heap_size and unsorted[left_index] > unsorted[largest]:
        ### [loop1]. largest = 6
        largest = left_index

    ### [loop1]. unsorted[right_index] = 1, unsorted[largest] = 3 // fail    
    if right_index < heap_size and unsorted[right_index] > unsorted[largest]:
        largest = right_index
    
    # 부모노드의 인덱스값이 바뀌었다면 자식노드의 값과 스위치

    ### [loop1]. largest = 6 , index = 3
    if largest != index:
        ### [loop1]. unsorted[3] = 6 , unsorted[6] = 4 스위치
        unsorted[largest], unsorted[index] = unsorted[index], unsorted[largest]
        # 재귀 함수
        heapify(unsorted, largest, heap_size)

#### 3. 실행

In [0]:
a = [7,2,9,4,3,8,6,1]

In [0]:
heap_sort(a)

[1, 2, 3, 4, 6, 7, 8, 9]

## 4월 29일 과제

### 평균 선형 시간 선택 알고리즘

- ref 1. https://iredays.tistory.com/81
- ref 2. https://yongy0ng2.tistory.com/57
- ref 3. https://blog.naver.com/PostView.nhn?blogId=taep0q&logNo=221388928834&parentCategoryNo=&categoryNo=12&viewDate=&isShowPopularPosts=true&from=search

#### 1. 평균 선형 시간 선택 알고리즘 함수

In [0]:
def select(a, start, last, target):
  # 원소가 하나뿐일 때
  if start == last: return a[start]
  
  # partition 처리 후 기준 인덱스 값을 받음
  q = partition(a, start, last)

  # k : 기준 원소에서 k번째 작은 원소
  k = q-start+1

  if target < k:
    # 왼쪽 그룹
    return select(a, start, q-1, target)
  elif target > k: 
    # 오른쪽 그룹
    return select(a, q+1, last, target-k)
  else:
    return a[q]


#### 2. 파티션 함수

In [0]:
def partition(a, start, last):

  pivot = a[last]

  i = start - 1

  for j in range(start,last):
    if a[j] <= pivot:
      i += 1
      a[i], a[j] = a[j], a[i]

  # 2구역의 첫 원소와 pivot값 교환
  a[i+1], a[last] = a[last], a[i+1]
  return i+1

#### 3. 실행

In [0]:
a = [31, 8, 48, 73, 11, 3, 20, 29, 65, 15]
target = 2
start = 0
last = len(a)-1

result = select(a, start, last, target)
print(result)

8


## 5월 6일 알고리즘 수업

### 최악의 경우 선형 시간 선택 알고리즘 (선택)

### 이진 검색 트리

- 계산 복잡성은 O(logn)으로 빠르지만 자료 입력, 삭제가 불가능
- 이진탐색트리의 핵심 연산은 검색(retreive), 삽입(insert), 삭제(delete) 세가지로 나뉨
- 각 노드의 왼쪽 서브트리에는 해당 노드의 값보다 작은 값, 오른쪽 서브트리에는 해당 노드의 값보다 큰값이라는 가정
- 중복된 노드가 없어야 함
- ref1. https://ratsgo.github.io/data%20structure&algorithm/2017/10/22/bst/
- ref2. https://geonlee.tistory.com/72

#### 1. 클래스 정의

In [0]:
# 노드 정의 (부모 노드1, 자식 노드2)
class Node(object):
  def __init__(self, data):
    # data : 부모 노드
    self.data = data
    # left, right : 자식 노드
    self.left = self.right = None

#### 2. 이진 검색 트리 구현

In [0]:
class BinarySearchTree(object):

  # 1. 초기화
  def __init__(self):
    # 최상위 노드
    self.root = None

  # 2. 삽입
  def insert(self, data):
    # data를 1개의 노드씩 받아서 insert_value 함수 실행
    self.root = self._insert_value(self.root, data)
    # 값을 넣었으면 True 반환
    return self.root is not None

  def _insert_value(self, node, data):
    # 부모 노드가 비워져있다면 부모 노드에 추가
    if node is None:
      node = Node(data)
    # 부모 노드에 값이 있다면 자식 노드에 추가
    else:
      # 부모 노드보다 작으면 left에 추가
      if data < node.data:
        node.left = self._insert_value(node.left, data)
      # 부모 노드보다 크다면 right에 추가
      else:
        node.right = self._insert_value(node.right, data)
    return node

  # 3. 탐색
  def find(self, key):
    # 리스트에서 찾고자하는 key값을 받아서 find_value 함수 실행 (실제 값)
    return self._find_value(self.root, key)

  # 삽입 완료된 root 노드에서 해당 값을 찾음
  def _find_value(self, root, key):
    # root에 값이 없거나 key값과 일치하면 값을 반환
    if root is None or root.data == key:
      # 값을 찾았으면 True, 못찾았으면 False 반환
      return root is not None

    # key값이 부모 노드보다 작다면 left 자식 노드로
    elif key < root.data:
      return self._find_value(root.left, key)
      
    # key값이 부모 노드보다 크다면 right 자식 노드로
    else:
      return self._find_value(root.right, key)

  # 4. 삭제
  def delete(self, key):
    # 리스트에서 삭제하고자하는 key값을 받아서 deletet_value 함수 실행
    self.root, deleted = self._delete_value(self.root, key)
    return deleted

  def _delete_value(self, node, key):
    # node값이 비었으면 빈값과 False 반환
    if node is None:
      return node, False

    # flag 선언
    deleted = False

    # node.data와 key값이 같으면 데이터 삭제
    if key == node.data:
      # flag 수정
      deleted = True

      # case3. 좌우 노드가 모두 존재할 경우
      if node.left and node.right:

        # 해당 노드와 right 자식 노드를 받음
        parent, child = node, node.right

        # left 자식 노드를 탐색하여 가장 작은값을 찾음
        # left 자식 노드의 부모 노드 값을 받아둠 (재 연결을 위함)
        while child.left is not None:
          parent, child = child, child.left

        # key값의 left 자식 노드 값을 child의 left 자식 노드에 붙임 (=가장 작은값 왼쪽에 붙임) 
        child.left = node.left

        # key 노드의 right 노드가 바로 가장 작은값일 때인 상황을 고려하기 위해 넣음
        if parent != node:
          # 가장 작은값 부모 노드에 가장 작은값의 right 자식노드를 left 자식노드로 붙임
          parent.left = child.right
          # 가장 작은값 right 자식 노드에 key값에 right 자식노드를 붙임
          child.right = node.right

        # 처리 완료된 child가 node가 됨
        node = child

      # case2. 좌,우 한 노드만 존재할 경우
      elif node.left or node.right:
        # 자식 노드를 그대로 끌어다 놓음
        node = node.left or node.right

      # case1. 자식노드가 없을경우
      else:
        # 해당 값 삭제
        node = None

    # key값이 작으면 left 자식노드로
    elif key < node.data:
      node.left, deleted = self._delete_value(node.left, key)
    # key값이 크면 right 자식노드로
    else:
      node.right, deleted = self._delete_value(node.right, key)

    return node, deleted

#### 3. 실행

In [0]:
array = [40, 4, 34, 45, 14, 55, 48, 13, 15, 49, 47]
bst = BinarySearchTree()

for x in array:
  bst.insert(x)

# Find
print(bst.find(15)) # True
print(bst.find(17)) # False

# Delete
print(bst.delete(55)) # True
print(bst.delete(14)) # True
print(bst.delete(11)) # False

True
False
True
True
False


## 5월 13일 알고리즘 수업

### 1. B-트리 알고리즘
#### [B-Tree 특성]
##### 1.root node가 leaf node인 경우를 제외하고는 항상 최소 2개의 children을 가진다.
##### 2. root node와 leaf node를 제외한 모든 node 들은 최소 [M/2], 최대 M개의 서브트리를 가진다.
##### 3. 모든 leaf node 들은 같은 level에 있어야한다.
##### 4. 새로운 key값은 leaf node에 삽입된다.
##### 5. node 내의 key 값들은 오름차순이다.
##### 6. leaf node는 최소 [M/2]-1개의 key를 가지고 있어야한다.
---------

- 리프 노드 : 자식 노드가 없는 노드
- https://potatoggg.tistory.com/174
- https://gist.github.com/natekupp/1763661

#### BTreeNode class 
##### B-Tree의 검색, 삽입, 삭제 함수 구현
------
##### 1. 초기화
##### 1.1 루트, 리프노드 초기화 함수
##### 1.2 로그 print 함수
##### 1.3 b-tree의 무결성을 확인하는 함수
------
##### 2. 검색
##### 2.1 val값을 받아 BTree 내에서 찾는 함수
------
##### 3. 삽입
##### 3.1 val값을 삽입해주는 함수
##### 3.2 오버플로우 발생 시 노드 분할 함수
------
##### 4. 삭제
##### 4.1 val값을 삭제해주는 함수
##### 4.2 언더플로우시 재조정해주는 함수
##### 4.3 재조정시 병합해주는 함수
##### 4.4 재조정시 최솟값을 구해주는 함수
##### 4.5 병합시 최댓값을 구해주는 함수

In [0]:
# bisect : 정렬된 리스트를 삽입 후에 다시 정렬할 필요 없도록 관리해주는 라이브러리
# https://docs.python.org/ko/dev/library/bisect.html
import bisect

class _BTreeNode(object):
    # 1. 초기화
    def __init__(self, values=None, children=None):
        # parent :  루트 노드
        # values : 리프 노드
        # children : 키 값, 자식 값
        self.parent = None
        self.values = values or []
        self.children = children

        # 값 업데이트시 재정렬 (삽입,삭제)
        if self.children:
            for i in self.children:
                i.parent = self

    # 1. 초기화 (값 출력1)
    def __str__(self):
        return 'Node(%x, %x, %r, %d)' % (
                id(self),
                id(self.parent),
                self.values,
                len(self.children) if self.children else 0)
        
    # 1. 초기화 (값 출력2)    
    def pretty_print(self, tab=''):
        print('%s%s' % (tab, self))
        if self.children:
            for i in self.children:
                i.pretty_print(tab + '   ')

    # 1. 초기화 (무결성 확인 : 재귀적으로 b-tree의 무결성을 확인)
    def check_valid(self, tree):
        # innerNode : 리프 노드
        # rootnode : 루트 노드
        innerNode = self.children is not None
        rootNode = self.parent is None

        # assert : 조건이 true여야 실행, false면 error
        # values에 값이 있다는 가정
        assert(self.values is not None)

        # 노드들의 최솟값 확인 (루트노드 제외)
        if not rootNode and innerNode:
            assert(tree.min_values <= len(self.values))

        # 노드들의 최댓값 확인
        assert(len(self.values) <= tree.max_values)

        # 루트노드가 리프노드가 아닌경우 최소 2명의 자식 값이 있어야함
        if rootNode and innerNode:
            assert(len(self.children) >= 2)

        # k개의 자식이 있는 리프 노드가 아닌경우 k-1개가 포함되어 있어야함
        if innerNode:
            assert((len(self.values) + 1) == len(self.children))
        
        # 값이 정렬되어 있는지 확인
        prev = None
        for i in self.values:
            if prev is not None:
                assert(i > prev)
            prev = i

        if self.children:
            for i in self.children:
                assert(i.parent is self)
                i.check_valid(tree)


    # 2. 검색
    def search(self, val):
        # values에서 찾고자하는 val의 위치를 찾음
        i = bisect.bisect_left(self.values, val)
        # 찾은 index i가 마지막 index가 아니고,(못찾음)
        # 해당값보다 작지않을 때 ( == 같을 때) 찾음
        if (i != len(self.values) and not val < self.values[i]):
            # 해당 값과 val값을 비교
            # 동일하면 return
            assert(self.values[i] == val)
            return (True, self, i)            

        # 만약 자식 값이 더 존재한다면 실행
        if self.children is not None:
            # 리프 노드 값을 재귀적으로 검색
            assert(len(self.children) >= i and self.children[i])
            return self.children[i].search(val)
        else:
            return (False, self, i)
   
    # 3. 삽입
    def add(self, tree, val, slot=None, childNodes=None):
        # 모든 삽입은 리프 노드에서 이뤄져야함
        # 부모 노드에게 재귀적으로 호출 (무결성 확인)
        # 노드 분할 결과 중간값을 부모노드에게 보냄
        assert(self.children is None or childNodes)

        # 리프노드에 값이 있을 때,
        innerNode = self.children is not None
        if innerNode:
            assert(childNodes and len(childNodes) == 2)
        else:
            assert(childNodes is None)
        
        # 삽입할 위치를 찾지못한 경우, 다음에서 찾음
        if slot is None:
            slot = bisect.bisect_left(self.values, val)

        # 현재 노드값에 삽입할 수 있는지 확인
        if len(self.values) < tree.max_values:
            self.values.insert(slot, val)
            tree.size += 1
            if childNodes:
                # 추가하려는 노드에서 부모를 참조하여 업데이트
                for i in childNodes:
                    i.parent = self
                self.children[slot:slot + 1] = childNodes
            # 작업 완료
            return True
        
        # 현재 노드가 가득찼으면 분할
        self._split_node(tree, val, slot, childNodes)
        return True

    # 3. 삽입 (값 삽입시 분할)
    def _split_node(self, tree, val=None, slot=None, childNodes=None):
        assert(val is None or (slot is not None))

        midList = [] if val is None else [ val ]
        if slot is None:
            slot = 0

        # 중앙값을 구함
        splitValues = self.values[0:slot] + midList + self.values[slot:]
        medianIdx = len(splitValues) // 2
        
        lv = splitValues[0:medianIdx]
        medianVal = splitValues[medianIdx]
        rv = splitValues[medianIdx + 1:]
        
        innerNode = self.children is not None

        if innerNode:
            if childNodes is not None:
                splitChildren = (self.children[0:slot] + 
                                 list(childNodes) + 
                                 self.children[slot + 1:])
            else:
                splitChildren = self.children
            lc = splitChildren[0:len(lv) + 1]
            rc = splitChildren[len(lv) + 1:]
        else:
            lc = None
            rc = None

        leftNode = _BTreeNode(lv, lc)
        rightNode = _BTreeNode(rv, rc)

        if self.parent:
            self.parent.add(tree,
                            medianVal,
                            None,
                            (leftNode, rightNode))
        else:
            # 새로운 루트노드를 만들고 트리의 깊이를 증가함
            newRoot = _BTreeNode([ medianVal ], [leftNode, rightNode])
            leftNode.parent = newRoot
            rightNode.parent = newRoot
            tree.root = newRoot
            tree.height += 1
            tree.size += 1

    # 4. 삭제 (삭제시 노드의 최솟값을 구함)
    def min_value(self, slot=0):
        if self.children:
            return self.children[slot].min_value()
        return self.values[0], self, 0
    # 4. 삭제 (재조정시 노드의 최댓값을 구함)
    def max_value(self, slot=None):
        if slot is None:
            slot = len(self.values) - 1
        if self.children:
            return self.children[slot + 1].max_value()
        return self.values[-1], self, len(self.values) - 1


    # 4. 삭제
    def delete(self, tree, val, slot=None):

        innerNode = self.children is not None        
        if slot is None:
            assert(slot is not None)
            slot = bisect.bisect_left(self.values, val)
        
        assert(slot != len(self.values) and self.values[slot] == val)
        
        if not innerNode:
            # 앞에서 삭제를 수행
            del self.values[slot]
            tree.size -= 1
            if len(self.values) < tree.min_values:
                # 리프 노드에서 언더플로우 발생시 재조정
                self._rebalance(tree)
        else:
            # 오른쪽 하위트리에서 최소값을 찾음
            # val을 대체하기 위해 구분 기호를 사용
            newSep, node, idx = self.min_value(slot + 1)
            self.values[slot] = newSep
            del node.values[idx]
            tree.size -= 1
            if len(node.values) < tree.min_values:
                node._rebalance(tree)

    # 4. 삭제 (삭제 후 언더플로우일 때 재조정)
    def _rebalance(self, tree):
        lsibling, rsibling, idx = self.get_siblings()
        
        # 루트노드에 형제가 없을때
        assert(rsibling or lsibling or self.parent is None)

        if self.parent is None:
            # 루트노드만을 위한 처리
            return

        innerNode = self.children is not None
        if innerNode:
            assert(rsibling is None or rsibling.children is not None)
            assert(lsibling is None or lsibling.children is not None)
        else:
            assert(rsibling is None or rsibling.children is None)
            assert(lsibling is None or lsibling.children is None)

        if not innerNode:
            if rsibling and len(rsibling.values) > tree.min_values:
                sepIdx = idx
                sepVal = self.parent.values[sepIdx]
                # 왼쪽 형제 리프노드에서 값을 빌려옴
                self.parent.values[sepIdx] = rsibling.values[0]
                del rsibling.values[0]
                self.values.append(sepVal)
                return
            elif lsibling and len(lsibling.values) > tree.min_values:
                sepIdx = idx - 1
                sepVal = self.parent.values[sepIdx]
                # 오른쪽 형제 리프노드에서 값을 빌려옴
                self.parent.values[sepIdx] = lsibling.values[-1]
                del lsibling.values[-1]
                self.values.insert(0, sepVal)
                return
                
        # 2개를 병합해야할 때
        if lsibling is not None:
            sepIdx = idx - 1
            ln = lsibling
            rn = self
        elif rsibling is not None:
            sepIdx = idx
            ln = self
            rn = rsibling
        else:
            assert(False)
        
        sepVal = self.parent.values[sepIdx]

        ln.values.append(sepVal)
        ln.values.extend(rn.values)
        del rn.values[:]
        del self.parent.values[sepIdx]
        assert(self.parent.children[sepIdx + 1] is rn)
        del self.parent.children[sepIdx + 1]
        if rn.children:
            ln.children.extend(rn.children)
            for i in rn.children:
                i.parent = ln

        if len(ln.values) > tree.max_values:
            # 새로 형성된 노드를 분할해야 함
            # 내부 노드를 병합할 때만 발생
            assert(innerNode)
            ln._split_node(tree)

        if len(self.parent.values) < tree.min_values:
            # rebalance the parent
            self.parent._rebalance(tree)            

        if self.parent.parent is None and not self.parent.values:
            tree.root = ln
            tree.root.parent = None

    # 4. 삭제 (재조정시 양쪽 인접노드를 가져옴)
    def get_siblings(self):
        if not self.parent:
            # 형제가 없는 노드
            return (None, None, 0)

        assert(self.parent.children)

        lsibling = None
        rsibling = None
        idx = 0

        for i, j in enumerate(self.parent.children):
            if j is self:
                if i != 0:
                    lsibling = self.parent.children[i - 1]
                if (i + 1) < len(self.parent.children):
                    rsibling = self.parent.children[i + 1]
                idx = i  
                break

        return (lsibling, rsibling, idx)

#### 2. BTree class
##### B-Tree의 작동 구현

In [0]:
class BTree(object):
    
    # B-Tree의 초기값을 설정
    def __init__(self, order):
        if order <= 2:
            raise ValueError("B-tree order must be at least 3")
        self.root = _BTreeNode()
        self.order = order
        self.max_values = order - 1
        self.min_values = self.max_values // 2
        self.height = 1
        self.size = 0
        
    def __str__(self):
        return 'height: %d items: %d m: %d root: %x' % (
                                    self.height, self.size,
                                    self.max_values + 1,
                                    id(self.root))

    # 값 추가
    def add(self, val):
        # 값을 추가할 리프 노드를 찾음
        found, node, slot = self.root.search(val)
        if found:
            # 값이 이미 존재하므로 추가 못함
            return False
        return node.add(self, val, slot, None)

    # 값 삭제
    def delete(self, val):
        # 값을 삭제할 리프 노드를 찾음
        found, node, slot = self.root.search(val)
        if not found:
            # 값이 존재하지않아 삭제 못함
            return False
        return node.delete(self, val, slot)

    # 값 찾기
    def search(self, val):
        return self.root.search(val)[0]

    def min(self):
        return self.root.min_value()[0]

    def max(self):
        return self.root.max_value()[0]
    

#### 3. 실행

In [0]:
# B트리 생성, 노드 크기의 최솟값 설정
# k = 5
tree = BTree(5)

# 삽입
a = [1,2,3,4,6,7,8,10,13,15,17,19,20,25,27,28,30,33,34,37,38,40,41,45]

print("삽입 시작!")

for i in a:
    tree.add(i)
    assert(tree.search(i))

print("삽입 완료!")
print("--------------------------------------------------------------")

# 검색
print("검색 시작!")

for i in a:
    assert(tree.search(i))
    
tree.root.pretty_print()
tree.root.check_valid(tree)

print("검색 완료!")
print("--------------------------------------------------------------")


# 삭제
print("삭제 시작!")

for i in a:
    tree.delete(i)
    tree.root.check_valid(tree)
print("삭제 완료!")
print("--------------------------------------------------------------")


삽입 시작!
삽입 완료!
--------------------------------------------------------------
검색 시작!
Node(7fd08d9e97b8, 9d4380, [13], 2)
   Node(7fd08d9e92e8, 7fd08d9e97b8, [3, 7], 3)
      Node(7fd08d9e9080, 7fd08d9e92e8, [1, 2], 0)
      Node(7fd08d9e9470, 7fd08d9e92e8, [4, 6], 0)
      Node(7fd08d9e9390, 7fd08d9e92e8, [8, 10], 0)
   Node(7fd08d9e9fd0, 7fd08d9e97b8, [19, 27, 33, 38], 5)
      Node(7fd08d9e9a90, 7fd08d9e9fd0, [15, 17], 0)
      Node(7fd08d9e9860, 7fd08d9e9fd0, [20, 25], 0)
      Node(7fd08d9e99b0, 7fd08d9e9fd0, [28, 30], 0)
      Node(7fd08d9e9c88, 7fd08d9e9fd0, [34, 37], 0)
      Node(7fd08d9d9c18, 7fd08d9e9fd0, [40, 41, 45], 0)
검색 완료!
--------------------------------------------------------------
삭제 시작!
삭제 완료!
--------------------------------------------------------------


결과값을 시각화하면 다음과 같다.

![대체 텍스트](https://postfiles.pstatic.net/MjAyMDA1MjNfMTU5/MDAxNTkwMTc4MjAxNDcw.U8TIrAgwwpodoM4AZrI6BlTmPzMmPt323GVZvDuoewMg.gLM4Sw-f8UP-MnEgwJLPr_kyOTBdqhMbT4Sf9Epr_U0g.PNG.dnjswns2280/b_tree.PNG?type=w773)

## 5월 20일 알고리즘 수업

### 행렬 경로 알고리즘 (재귀호출)

In [0]:
def matrixPath(arr,i,j):
  if i == 0 and j == 0:
    return arr[0][0]

  elif i == 0:
    return arr[i][j] + matrixPath(arr,i,j-1)

  elif j == 0:
    return arr[i][j] + matrixPath(arr,i-1,j)

  else:
    return arr[i][j] + max(matrixPath(arr, i-1, j), matrixPath(arr, i, j-1))

In [0]:
arr = [[6,7,12,5],
      [5,3,11,18],
      [7,17,3,3],
      [8,10,14,9]]

max_value = matrixPath(arr,3,3)
print('최댓값:',max_value)

최댓값: 68


### 행렬 경로 알고리즘 (동적 프로그래밍)

In [0]:
def matrixPath(n):

  for i in range(1,len(n)):
    for j in range(1,len(n)):
      n[0][0] = n[i][j] + max(n[i-1][j], n[i][j-1])
      
  return n[0][0]

In [0]:
arr = [[6,7,12,5],
      [5,3,11,18],
      [7,17,3,3],
      [8,10,14,9]]

max_value = matrixPath(arr)
print('최댓값:',max_value)

최댓값: 23


## 6월 3일 알고리즘 수업

### 돌 놓기 문제

In [11]:
import numpy as np

w = [[6, -8, 11],[7, 10, 12], [12, 14, 7],
      [-5, 9, 4], [5, 7, 8], [3, 13, -2],
      [11, 8, 9], [3, 5, 4]]

# p 다음에 올 패턴을 케이스별로 나눔
def getAvailPat(p):
    if p == 1:
        return 2, 3

    elif p == 2:
        return 1, 3, 4

    elif p == 3:
        return 1, 2

    else:
        return (2,)

# 패턴을 받아서 해당하는 값을 반환
def getPatVal(i, p):

    global w

    if p == 1:
        return w[i][0]

    elif p == 2:
        return w[i][1]

    elif p == 3:
        return w[i][2]

    else:
        return w[i][0]+w[i][2]

def pebble (i, p):

    if i == 0:
        return getPatVal(0, p)

    else:
        # pats : 다음에 올 값
        maxVal = 0
        pats = getAvailPat(p)

        for q in range(1, 5):
            if q in pats:
                tmp = pebble(i-1, q)
                if tmp > maxVal:
                    maxVal = tmp

    return maxVal+getPatVal(i, p)

def dp_pebble (n):

    peb = np.zeros((n+1, 4))

    for p in range(1, 5):
        peb[0][p-1] = getPatVal(0, p)

    # 큰 값을 리턴함
    for i in range(1, n+1):      
        for p in getAvailPat(np.argmax(peb[i-1])+1):        
            peb[i][p-1] = max(peb[i-1]) + getPatVal(i, p)

    return max(peb[n-1]), peb

        
maxVal, peb = dp_pebble(7)
print(maxVal)
print(peb)

101.0
[[  6.  -8.  11.  17.]
 [  0.  27.   0.   0.]
 [ 39.   0.  34.  46.]
 [  0.  55.   0.   0.]
 [ 60.   0.  63.  68.]
 [  0.  81.   0.   0.]
 [ 92.   0.  90. 101.]
 [  0. 106.   0.   0.]]
